from datetime import datetime

import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from pytrends.request import TrendReq
from streamlit.components.v1 import html

# Sidebar with dropdown list for country selection
st.sidebar.title("Select Country")
country_label = st.sidebar.selectbox(
    "Choose a Country",
    options={
        "ARGENTINA": "argentina",
        "AUSTRALIA": "australia",
        "AUSTRIA": "austria",
        "BANGLADESH": "bangladesh",
        "BELGIUM": "belgium",
        "BRAZIL": "brazil",
        "CANADA": "canada",
        "COLOMBIA": "colombia",
        "CZECH REPUBLIC": "czech_republic",
        "DENMARK": "denmark",
        "EGYPT": "egypt",
        "ETHIOPIA": "ethiopia",
        "FINLAND": "finland",
        "FRANCE": "france",
        "GERMANY": "germany",
        "GREECE": "greece",
        "HONG KONG": "hong_kong",
        "HUNGARY": "hungary",
        "INDIA": "india",
        "INDONESIA": "indonesia",
        "IRAN": "iran",
        "IRELAND": "ireland",
        "ISRAEL": "israel",
        "ITALY": "italy",
        "JAPAN": "japan",
        "MALAYSIA": "malaysia",
        "MEXICO": "mexico",
        "NETHERLANDS": "netherlands",
        "NEW ZEALAND": "new_zealand",
        "NIGERIA": "nigeria",
        "NORWAY": "norway",
        "PAKISTAN": "pakistan",
        "PHILIPPINES": "philippines",
        "POLAND": "poland",
        "PORTUGAL": "portugal",
        "RUSSIA": "russia",
        "SAUDI ARABIA": "saudi_arabia",
        "SINGAPORE": "singapore",
        "SOUTH AFRICA": "south_africa",
        "SOUTH KOREA": "south_korea",
        "SPAIN": "spain",
        "SWEDEN": "sweden",
        "SWITZERLAND": "switzerland",
        "THAILAND": "thailand",
        "TURKEY": "turkey",
        "UKRAINE": "ukraine",
        "UNITED KINGDOM": "united_kingdom",
        "UNITED STATES": "united_states",
        "VIETNAM": "vietnam",
    },
)
country = country_label.lower().replace(" ", "_")
# Add Ko-fi widget to the Streamlit app

# st.sidebar.title("Select Geo Location")
# geo = st.sidebar.selectbox(
#     "Choose a geo location",
#     options={
#         "World": '',
#         "United States": 'US',
#         "Canada": 'CA',
#         "Brazil": 'BR',
#         "United Kingdom": 'GB',
#         "Germany": 'DE',
#         "France": 'FR',
#         "Italy": 'IT',
#         "Spain": 'ES',
#         "Australia": 'AU',
#         "India": 'IN',
#         "Japan": 'JP',
#         "South Korea": 'KR',
#         "Mexico": 'MX',
#         "Russia": 'RU',
#         "South Africa": 'ZA'
#     }
# )

# Sidebar with dropdown list for category selection
# st.sidebar.title("Select Category")
# category = st.sidebar.selectbox(
#     "Choose a category",
#     options={
#         "All categories": 0,
#         "Arts & Entertainment": 3,
#         "Celebrities & Entertainment News": 184,
#         "Comics & Animation": 316,
#         "Animated Films": 1104,
#         "Anime & Manga": 317,
#         "Cartoons": 319,
#         "Comics": 318,
#         "Entertainment Industry": 612,
#         "Film & TV Industry": 1116,
#         "Film & TV Awards": 1108,
#         "Film & TV Production": 1117,
#         "Recording Industry": 1115,
#         "Music Awards": 1113,
#         "Record Labels": 1114,
#         "Events & Listings": 569,
#         "Clubs & Nightlife": 188,
#         "Concerts & Music Festivals": 891,
#         "Film Festivals": 1086,
#         "Live Sporting Events": 1273,
#         "Movie Listings & Theater Showtimes": 1085,
#         "Ticket Sales": 614,
#         "Fun & Trivia": 539,
#         "Dress-Up & Fashion Games": 1173,
#         "Flash-Based Entertainment": 447,
#         "Fun Tests & Silly Surveys": 1174,
#         "Humor": 182,
#         "Comedy Films": 1095,
#         "Live Comedy": 895,
#         "Political Humor": 1180,
#         "Spoofs & Satire": 1244,
#         "TV Comedies": 1047,
#         "Movies": 34,
#         "Action & Adventure Films": 1097,
#         "Martial Arts Films": 1101,
#         "Superhero Films": 1100,
#         "Western Films": 1099,
#         "Animated Films": 1104,
#         "Bollywood & South Asian Film": 360,
#         "Classic Films": 1102,
#         "Silent Films": 1098,
#         "Comedy Films": 1095,
#         "Cult & Indie Films": 1103,
#         "Documentary Films": 1072,
#         "Drama Films": 1094,
#         "DVD & Video Shopping": 210,
#         "DVD & Video Rentals": 1145,
#         "Family Films": 1291,
#         "Film & TV Awards": 1108,
#         "Film Festivals": 1086,
#         "Horror Films": 615,
#         "Movie Memorabilia": 213,
#         "Movie Reference": 1106,
#         "Movie Reviews & Previews": 1107,
#         "Musical Films": 1105,
#         "Romance Films": 1310,
#         "Science Fiction & Fantasy Films": 616,
#         "Thriller, Crime & Mystery Films": 1096,
#         "Music & Audio": 35,
#         "CD & Audio Shopping": 217,
#         "Classical Music": 586,
#         "Opera": 1185,
#         "Country Music": 587,
#         "Dance & Electronic Music": 588,
#         "Experimental & Industrial Music": 1022,
#         "Folk & Traditional Music": 1023,
#         "Jazz & Blues": 589,
#         "Blues": 1040,
#         "Jazz": 42,
#         "Latin Pop": 1285,
#         "Music Art & Memorabilia": 218,
#         "Music Education & Instruction": 1087,
#         "Music Equipment & Technology": 1024,
#         "DJ Resources & Equipment": 1025,
#         "Music Recording Technology": 1026,
#         "Musical Instruments": 216,
#         "Drums & Percussion": 1327,
#         "Guitars": 1325,
#         "Pianos & Keyboards": 1326,
#         "Samples & Sound Libraries": 1091,
#         "Music Reference": 1027,
#         "Music Composition & Theory": 1028,
#         "Sheet Music": 892,
#         "Song Lyrics & Tabs": 617,
#         "Music Streams & Downloads": 220,
#         "Pop Music": 1021,
#         "Radio": 215,
#         "Podcasting": 809,
#         "Talk Radio": 1186,
#         "Religious Music": 1020,
#         "Christian & Gospel Music": 585,
#         "Rock Music": 590,
#         "Classic Rock & Oldies": 1037,
#         "Hard Rock & Progressive": 1035,
#         "Indie & Alternative Music": 1038,
#         "Metal (Music)": 1036,
#         "Punk (Music)": 1041,
#         "Soundtracks": 893,
#         "Urban & Hip-Hop": 592,
#         "Rap & Hip-Hop": 1030,
#         "Reggaeton": 1242,
#         "Soul & R&B": 1039,
#         "Vocals & Show Tunes": 618,
#         "World Music": 593,
#         "African Music": 1208,
#         "Arab & Middle Eastern Music": 1034,
#         "East Asian Music": 1033,
#         "Latin American Music": 591,
#         "Brazilian Music": 1287,
#         "Latin Pop": 1285,
#         "Reggaeton": 1242,
#         "Salsa & Tropical Music": 1286,
#         "Reggae & Caribbean Music": 1031,
#         "Reggaeton": 1242,
#         "South Asian Music": 1032,
#         "Offbeat": 33,
#         "Edgy & Bizarre": 538,
#         "Occult & Paranormal": 449,
#         "Online Media": 613,
#         "Flash-Based Entertainment": 447,
#         "Music Streams & Downloads": 220,
#         "Online Games": 105,
#         "Massive Multiplayer": 935,
#         "Online Image Galleries": 1222,
#         "Photo & Image Sharing": 978,
#         "Photo Rating Sites": 320,
#         "Stock Photography": 574,
#         "Online Video": 211,
#         "Video Sharing": 979,
#         "Web Portals": 301,
#         "Webcams & Virtual Tours": 575,
#         "Performing Arts": 23,
#         "Acting & Theater": 894,
#         "Broadway & Musical Theater": 1243,
#         "Dance": 581,
#         "Opera": 1185,
#         "TV & Video": 36,
#         "Online Video": 211,
#         "Video Sharing": 979,
#         "TV Commercials": 1055,
#         "TV Guides & Reference": 1187,
#         "TV Networks & Stations": 359,
#         "TV Shows & Programs": 358,
#         "TV Comedies": 1047,
#         "TV Dramas": 1193,
#         "TV Crime & Legal Shows": 1111,
#         "TV Medical Shows": 1194,
#         "TV Soap Operas": 357,
#         "TV Family-Oriented Shows": 1110,
#         "TV Game Shows": 1050,
#         "TV Reality Shows": 1049,
#         "TV Sci-Fi & Fantasy Shows": 1112,
#         "TV Talk Shows": 1048,
#         "Visual Art & Design": 24,
#         "Architecture": 477,
#         "Art & Craft Supplies": 1361,
#         "Arts Education": 1195,
#         "Design": 653,
#         "CAD & CAM": 1300,
#         "Graphic Design": 654,
#         "Industrial & Product Design": 655,
#         "Interior Design": 656,
#         "Painting": 1167,
#         "Photographic & Digital Arts": 439,
#         "Camera & Photo Equipment": 573,
#         "Binoculars, Telescopes & Optical Devices": 1384,
#         "Cameras & Camcorders": 306,
#         "Camcorders": 308,
#         "Camera Lenses": 1383,
#         "Cameras": 307,
#         "Photo & Video Software": 577,
#         "Video File Formats & Codecs": 1315,
#         "Autos & Vehicles": 47,
#         "Automotive Industry": 1190,
#         "Bicycles & Accessories": 1191,
#         "Boats & Watercraft": 1140,
#         "Campers & RVs": 1213,
#         "Classic Vehicles": 1013,
#         "Commercial Vehicles": 1214,
#         "Cargo Trucks & Trailers": 1215,
#         "Custom & Performance Vehicles": 806,
#         "Hybrid & Alternative Vehicles": 810,
#         "Electric & Plug-In Vehicles": 1380,
#         "Microcars & City Cars": 1317,
#         "Motorcycles": 273,
#         "Off-Road Vehicles": 148,
#         "Personal Aircraft": 1147,
#         "Scooters & Mopeds": 1212,
#         "Trucks & SUVs": 610,
#         "SUVs": 1057,
#         "Trucks": 1056,
#         "Vans & Minivans": 1058,
#         "Vehicle Brands": 815,
#         "Acura": 820,
#         "Audi": 821,
#         "Bentley": 1059,
#         "BMW": 822,
#         "Buick": 1060,
#         "Cadillac": 823,
#         "Chevrolet": 826,
#         "Chrysler": 833,
#         "Citroën": 834,
#         "Dodge": 836,
#         "Ferrari": 1061,
#         "Fiat": 838,
#         "Ford": 840,
#         "GM-Daewoo": 896,
#         "GMC": 842,
#         "Honda": 843,
#         "Hummer": 1062,
#         "Hyundai": 845,
#         "Isuzu": 1378,
#         "Jaguar": 1063,
#         "Jeep": 846,
#         "Kia": 848,
#         "Lamborghini": 1064,
#         "Land Rover": 1065,
#         "Lexus": 849,
#         "Lincoln": 850,
#         "Maserati": 1066,
#         "Mazda": 851,
#         "Mercedes-Benz": 852,
#         "Mercury": 853,
#         "Mini": 1067,
#         "Mitsubishi": 854,
#         "Nissan": 855,
#         "Infiniti": 1377,
#         "Peugeot": 856,
#         "Pontiac": 857,
#         "Porsche": 858,
#         "Renault-Samsung": 859,
#         "Rolls-Royce": 1068,
#         "Saab": 897,
#         "Saturn": 860,
#         "Subaru": 861,
#         "Suzuki": 1070,
#         "Toyota": 863,
#         "Scion": 1069,
#         "Vauxhall-Opel": 898,
#         "Volkswagen": 865,
#         "Volvo": 867,
#         "Vehicle Codes & Driving Laws": 1294,
#         "Drunk Driving Law": 968,
#         "Vehicle Licensing & Registration": 170,
#         "Vehicle Maintenance": 138,
#         "Vehicle Parts & Accessories": 89,
#         "Auto Exterior": 1217,
#         "Auto Interior": 1218,
#         "Car Electronics": 1188,
#         "Car Audio": 230,
#         "Car Video": 1189,
#         "GPS & Navigation": 794,
#         "Engine & Transmission": 1216,
#         "Vehicle Fuels & Lubricants": 1269,
#         "Vehicle Wheels & Tires": 438,
#         "Vehicle Shopping": 473,
#         "Fuel Economy & Gas Prices": 1268,
#         "Vehicle Specs, Reviews & Comparisons": 1267,
#         "Vehicle Shows": 803,
#         "Beauty & Fitness": 44,
#         "Beauty Pageants": 1219,
#         "Body Art": 239,
#         "Cosmetic Procedures": 1220,
#         "Cosmetic Surgery": 238,
#         "Cosmetology & Beauty Professionals": 147,
#         "Face & Body Care": 143,
#         "Hygiene & Toiletries": 244,
#         "Make-Up & Cosmetics": 234,
#         "Perfumes & Fragrances": 242,
#         "Skin & Nail Care": 93,
#         "Unwanted Body & Facial Hair Removal": 144,
#         "Fashion & Style": 185,
#         "Fashion Designers & Collections": 98,
#         "Fashion Modeling": 1155,
#         "Fitness": 94,
#         "Bodybuilding": 241,
#         "Yoga & Pilates": 611,
#         "Hair Care": 146,
#         "Hair Loss": 235,
#         "Spas & Beauty Services": 145,
#         "Massage Therapy": 557,
#         "Weight Loss": 236,
#         "Books & Literature": 22,
#         "Biographies & Quotations": 690,
#         "Book Retailers": 355,
#         "Children's Literature": 1183,
#         "E-Books": 608,
#         "Fan Fiction": 540,
#         "Literary Classics": 1184,
#         "Magazines": 412,
#         "Poetry": 565,
#         "Writers Resources": 1177,
#         "Business & Industrial": 12,
#         "Advertising & Marketing": 25,
#         "Marketing Services": 83,
#         "Loyalty Cards & Programs": 1309,
#         "Public Relations": 327,
#         "Search Engine Optimization & Marketing": 84,
#         "Telemarketing": 328,
#         "Aerospace & Defense": 356,
#         "Defense Industry": 669,
#         "Space Technology": 668,
#         "Agriculture & Forestry": 46,
#         "Agricultural Equipment": 748,
#         "Aquaculture": 747,
#         "Crops & Seed": 749,
#         "Food Production": 621,
#         "Forestry": 750,
#         "Horticulture": 751,
#         "Livestock": 752,
#         "Automotive Industry": 1190,
#         "Business Education": 799,
#         "Business Finance": 1138,
#         "Commercial Lending": 1160,
#         "Investment Banking": 1139,
#         "Risk Management": 620,
#         "Venture Capital": 905,
#         "Business News": 784,
#         "Company News": 1179,
#         "Company Earnings": 1240,
#         "Mergers & Acquisitions": 1241,
#         "Economy News": 1164,
#         "Financial Markets": 1163,
#         "Fiscal Policy News": 1165,
#         "Business Operations": 1159,
#         "Business Plans & Presentations": 336,
#         "Human Resources": 157,
#         "Compensation & Benefits": 723,
#         "Corporate Training": 331,
#         "Payroll Services": 724,
#         "Recruitment & Staffing": 330,
#         "Management": 338,
#         "Business Process": 721,
#         "Project Management": 1360,
#         "Project Management Software": 1359,
#         "Strategic Planning": 722,
#         "Supply Chain Management": 801,
#         "Business Services": 329,
#         "Advertising & Marketing": 25,
#         "Marketing Services": 83,
#         "Loyalty Cards & Programs": 1309,
#         "Public Relations": 327,
#         "Search Engine Optimization & Marketing": 84,
#         "Telemarketing": 328,
#         "Consulting": 1162,
#         "Corporate Events": 334,
#         "Trade Shows & Conventions": 335,
#         "E-Commerce Services": 340,
#         "Merchant Services & Payment Systems": 280,
#         "Fire & Security Services": 726,
#         "Knowledge Management": 800,
#         "Office Services": 28,
#         "Office & Facilities Management": 337,
#         "Office Supplies": 95,
#         "Business Cards & Stationary": 1375,
#         "Office Furniture": 333,
#         "Printers, Copiers & Fax": 1330,
#         "Copiers": 1331,
#         "Fax Machines": 1332,
#         "Ink & Toner": 1333,
#         "Printers": 494,
#         "Scanners": 495,
#         "Outsourcing": 718,
#         "Photo & Video Services": 576,
#         "Stock Photography": 574,
#         "Physical Asset Management": 719,
#         "Quality Control & Tracking": 720,
#         "Signage": 1076,
#         "Writing & Editing Services": 725,
#         "Chemicals Industry": 288,
#         "Agrochemicals": 670,
#         "Cleaning Agents": 671,
#         "Coatings & Adhesives": 672,
#         "Dyes & Pigments": 673,
#         "Plastics & Polymers": 674,
#         "Construction & Maintenance": 48,
#         "Building Materials & Supplies": 650,
#         "Doors & Windows": 827,
#         "HVAC & Climate Control": 828,
#         "Nails Screws & Fasteners": 829,
#         "Plumbing Fixtures & Equipment": 830,
#         "Wood & Plastics": 831,
#         "Civil Engineering": 651,
#         "Construction Consulting & Contracting": 652,
#         "Urban & Regional Planning": 686,
#         "Energy & Utilities": 233,
#         "Electricity": 658,
#         "Nuclear Energy": 954,
#         "Oil & Gas": 659,
#         "Vehicle Fuels & Lubricants": 1269,
#         "Renewable & Alternative Energy": 657,
#         "Waste Management": 660,
#         "Recycling": 1307,
#         "Water Supply & Treatment": 1349,
#         "Enterprise Technology": 77,
#         "Customer Relationship Management (CRM)": 341,
#         "Data Management": 343,
#         "E-Commerce Services": 340,
#         "Merchant Services & Payment Systems": 280,
#         "Enterprise Resource Planning (ERP)": 342,
#         "Entertainment Industry": 612,
#         "Film & TV Industry": 1116,
#         "Film & TV Awards": 1108,
#         "Film & TV Production": 1117,
#         "Recording Industry": 1115,
#         "Music Awards": 1113,
#         "Record Labels": 1114,
#         "Hospitality Industry": 955,
#         "Event Planning": 956,
#         "Food Service": 957,
#         "Grocery & Food Retailers": 121,
#         "Restaurant Supply": 816,
#         "Industrial Materials & Equipment": 287,
#         "Fluid Handling": 1152,
#         "Valves Hoses & Fittings": 839,
#         "Generators": 835,
#         "Heavy Machinery": 837,
#         "Manufacturing": 49,
#         "Factory Automation": 661,
#         "Metals & Mining": 606,
#         "Pharmaceuticals & Biotech": 255,
#         "Printing & Publishing": 1176,
#         "Document & Printing Services": 332,
#         "Business Cards & Stationary": 1375,
#         "Journalism & News Industry": 1204,
#         "Professional & Trade Associations": 1199,
#         "Retail Trade": 841,
#         "Retail Equipment & Technology": 844,
#         "Small Business": 551,
#         "Business Formation": 1200,
#         "Home Office": 727,
#         "MLM & Business Opportunities": 552,
#         "Textiles & Nonwovens": 566,
#         "Transportation & Logistics": 50,
#         "Aviation": 662,
#         "Distribution & Logistics": 664,
#         "Freight & Trucking": 289,
#         "Cargo Trucks & Trailers": 1215,
#         "Import & Export": 354,
#         "Mail & Package Delivery": 1150,
#         "Couriers & Messengers": 663,
#         "Maritime Transport": 665,
#         "Moving & Relocation": 291,
#         "Packaging": 290,
#         "Parking": 1306,
#         "Airport Parking & Transportation": 1245,
#         "Public Storage": 1347,
#         "Rail Transport": 666,
#         "Urban Transport": 667,
#         "Computers & Electronics": 5,
#         "CAD & CAM": 1300,
#         "Computer Hardware": 30,
#         "Computer Components": 717,
#         "Chips & Processors": 741,
#         "Computer Memory": 226,
#         "Sound & Video Cards": 740,
#         "Computer Drives & Storage": 496,
#         "CD & DVD Drives & Burners": 1321,
#         "CD & DVD Storage Media": 1322,
#         "Computer Memory": 226,
#         "Data Backup & Recovery": 1323,
#         "Flash Drives & Memory Cards": 1318,
#         "Hard Drives": 1320,
#         "Memory Card Readers": 1319,
#         "Network Storage": 729,
#         "Computer Peripherals": 312,
#         "Computer Monitors & Displays": 487,
#         "Input Devices": 493,
#         "Printers, Copiers & Fax": 1330,
#         "Copiers": 1331,
#         "Fax Machines": 1332,
#         "Ink & Toner": 1333,
#         "Printers": 494,
#         "Scanners": 495,
#         "Computer Servers": 728,
#         "Desktop Computers": 309,
#         "Hardware Modding & Tuning": 739,
#         "Laptops & Notebooks": 310,
#         "Tablet PCs": 1277,
#         "Computer Security": 314,
#         "Antivirus & Malware": 315,
#         "Network Security": 344,
#         "Consumer Electronics": 78,
#         "Audio Equipment": 361,
#         "Headphones": 1396,
#         "MP3 & Portable Media Players": 227,
#         "Speakers": 1158,
#         "Stereo Systems & Components": 91,
#         "Camera & Photo Equipment": 573,
#         "Binoculars, Telescopes & Optical Devices": 1384,
#         "Cameras & Camcorders": 306,
#         "Camcorders": 308,
#         "Camera Lenses": 1383,
#         "Cameras": 307,
#         "Car Electronics": 1188,
#         "Car Audio": 230,
#         "Car Video": 1189,
#         "GPS & Navigation": 794,
#         "Electronic Accessories": 1192,
#         "Gadgets & Portable Electronics": 362,
#         "E-Book Readers": 1324,
#         "Handheld Game Consoles": 1046,
#         "MP3 & Portable Media Players": 227,
#         "PDAs & Handhelds": 228,
#         "Game Systems & Consoles": 899,
#         "Handheld Game Consoles": 1046,
#         "Nintendo": 1043,
#         "Sony PlayStation": 1044,
#         "Xbox": 1045,
#         "GPS & Navigation": 794,
#         "TV & Video Equipment": 229,
#         "DVRs & Set-Top Boxes": 1393,
#         "Home Theater Systems": 1157,
#         "Projectors & Screens": 1334,
#         "Televisions": 305,
#         "HDTVs": 1354,
#         "LCD TVs": 1356,
#         "Plasma TVs": 1355,
#         "Projection TVs": 1357,
#         "Video Players & Recorders": 492,
#         "Blu-Ray Players & Recorders": 1394,
#         "DVD Players & Recorders": 1395,
#         "Electronics & Electrical": 434,
#         "Data Sheets & Electronics Reference": 900,
#         "Electromechanical Devices": 743,
#         "Electronic Components": 742,
#         "Optoelectronics & Fiber": 744,
#         "Power Supplies": 745,
#         "Test & Measurement": 746,
#         "Enterprise Technology": 77,
#         "Customer Relationship Management (CRM)": 341,
#         "Data Management": 343,
#         "E-Commerce Services": 340,
#         "Merchant Services & Payment Systems": 280,
#         "Enterprise Resource Planning (ERP)": 342,
#         "Networking": 311,
#         "Data Formats & Protocols": 488,
#         "Distributed & Parallel Computing": 1298,
#         "Network Monitoring & Management": 347,
#         "Networking Equipment": 346,
#         "VPN & Remote Access": 1279,
#         "Programming": 31,
#         "C & C++": 731,
#         "Developer Jobs": 802,
#         "Development Tools": 730,
#         "Java": 732,
#         "Scripting Languages": 733,
#         "Windows & .NET": 734,
#         "Software": 32,
#         "Business & Productivity Software": 498,
#         "Accounting & Financial Software": 1341,
#         "Calendar & Scheduling Software": 1358,
#         "Presentation Software": 1346,
#         "Project Management Software": 1359,
#         "Spreadsheet Software": 1344,
#         "Word Processing Software": 1345,
#         "Device Drivers": 225,
#         "Educational Software": 804,
#         "Freeware & Shareware": 901,
#         "Internet Software": 807,
#         "Content Management": 808,
#         "Internet Clients & Browsers": 304,
#         "Proxying & Filtering": 902,
#         "Mobile Apps & Add-Ons": 1109,
#         "Ringtones & Mobile Goodies": 532,
#         "Multimedia Software": 497,
#         "Audio & Music Software": 1089,
#         "Audio Files Formats & Codecs": 1092,
#         "Desktop Publishing": 1088,
#         "Fonts": 805,
#         "Graphics & Animation Software": 486,
#         "Media Players": 1090,
#         "Photo & Video Software": 577,
#         "Video File Formats & Codecs": 1315,
#         "Open Source": 313,
#         "Operating Systems": 303,
#         "Linux & Unix": 736,
#         "Mac OS": 735,
#         "Mobile OS": 1382,
#         "Windows OS": 737,
#         "Software Utilities": 224,
#         "Web Apps & Online Tools": 1142,
#         "Technical Support": 567,
#         "Technology News": 785,
#         "Finance": 7,
#         "Accounting & Auditing": 278,
#         "Accounting & Financial Software": 1341,
#         "Tax Preparation & Planning": 1283,
#         "Banking": 37,
#         "Credit & Lending": 279,
#         "Auto Financing": 468,
#         "College Financing": 813,
#         "Credit Cards": 811,
#         "Debt Management": 812,
#         "Home Financing": 466,
#         "Currencies & Foreign Exchange": 814,
#         "Financial Planning": 903,
#         "Grants & Financial Assistance": 1282,
#         "College Financing": 813,
#         "Insurance": 38,
#         "Auto Insurance": 467,
#         "Health Insurance": 249,
#         "Home Insurance": 465,
#         "Investing": 107,
#         "Commodities & Futures Trading": 904,
#         "Retirement & Pension": 619,
#         "Food & Drink": 71,
#         "Alcoholic Beverages": 277,
#         "Beer": 404,
#         "Liquor": 406,
#         "Wine": 405,
#         "Candy & Sweets": 906,
#         "Cooking & Recipes": 122,
#         "Baked Goods": 907,
#         "Fruits & Vegetables": 908,
#         "Meat & Seafood": 909,
#         "Soups & Stews": 910,
#         "Vegetarian Cuisine": 825,
#         "World Cuisines": 911,
#         "Asian Cuisine": 912,
#         "Latin American Cuisine": 913,
#         "Mediterranean Cuisine": 914,
#         "North American Cuisine": 915,
#         "Culinary Training": 297,
#         "Grocery & Food Retailers": 121,
#         "Non-Alcoholic Beverages": 560,
#         "Coffee & Tea": 916,
#         "Restaurants": 276,
#         "Dining Guides": 917,
#         "Fast Food": 918,
#         "Restaurant Supply": 816,
#         "Games": 8,
#         "Arcade & Coin-Op Games": 919,
#         "Board Games": 920,
#         "Chess & Abstract Strategy Games": 921,
#         "Miniatures & Wargaming": 922,
#         "Card Games": 39,
#         "Collectible Card Games": 923,
#         "Poker & Casino Games": 924,
#         "Computer & Video Games": 41,
#         "Action & Platform Games": 1311,
#         "Adventure Games": 925,
#         "Casual Games": 926,
#         "Driving & Racing Games": 927,
#         "Fighting Games": 928,
#         "Game Systems & Consoles": 899,
#         "Handheld Game Consoles": 1046,
#         "Nintendo": 1043,
#         "Sony PlayStation": 1044,
#         "Xbox": 1045,
#         "Gaming Media & Reference": 1343,
#         "Game Cheats & Hints": 381,
#         "Music & Dance Games": 929,
#         "Shooter Games": 930,
#         "Simulation Games": 931,
#         "Sports Games": 932,
#         "Strategy Games": 933,
#         "Video Game Emulation": 1342,
#         "Video Game Retailers": 1146,
#         "Family-Oriented Games & Activities": 1290,
#         "Drawing & Coloring": 1397,
#         "Dress-Up & Fashion Games": 1173,
#         "Online Games": 105,
#         "Massive Multiplayer": 935,
#         "Party Games": 936,
#         "Puzzles & Brainteasers": 937,
#         "Roleplaying Games": 622,
#         "Table Games": 938,
#         "Billiards": 939,
#         "Table Tennis": 940,
#         "Health": 45,
#         "Aging & Geriatrics": 623,
#         "Alzheimer's Disease": 624,
#         "Alternative & Natural Medicine": 499,
#         "Acupuncture & Chinese Medicine": 1239,
#         "Cleansing & Detoxification": 1238,
#         "Health Conditions": 419,
#         "AIDS & HIV": 625,
#         "Allergies": 626,
#         "Arthritis": 628,
#         "Cancer": 429,
#         "Cold & Flu": 629,
#         "Diabetes": 630,
#         "Ear Nose & Throat": 1211,
#         "Eating Disorders": 571,
#         "Endocrine Conditions": 1328,
#         "Diabetes": 630,
#         "Thyroid Conditions": 1329,
#         "Genetic Disorders": 941,
#         "GERD & Digestive Disorders": 638,
#         "Heart & Hypertension": 559,
#         "Infectious Diseases": 632,
#         "Cold & Flu": 629,
#         "Parasites & Parasitic Diseases": 1262,
#         "Sexually Transmitted Diseases": 421,
#         "AIDS & HIV": 625,
#         "Vaccines & Immunizations": 1263,
#         "Injury": 817,
#         "Neurological Disorders": 942,
#         "Alzheimer's Disease": 624,
#         "Obesity": 818,
#         "Pain Management": 819,
#         "Headaches & Migraines": 631,
#         "Respiratory Conditions": 824,
#         "Asthma": 627,
#         "Skin Conditions": 420,
#         "Sleep Disorders": 633,
#         "Health Education & Medical Training": 254,
#         "Health Foundations & Medical Research": 252,
#         "Health News": 1253,
#         "Health Policy": 1256,
#         "Medical Devices & Equipment": 251,
#         "Assistive Technology": 1352,
#         "Mobility Equipment & Accessories": 1353,
#         "Medical Facilities & Services": 256,
#         "Doctors' Offices": 634,
#         "Hospitals & Treatment Centers": 250,
#         "Medical Procedures": 635,
#         "Medical Tests & Exams": 943,
#         "Surgery": 944,
#         "Cosmetic Surgery": 238,
#         "Vaccines & Immunizations": 1263,
#         "Physical Therapy": 500,
#         "Medical Literature & Resources": 253,
#         "Medical Photos & Illustration": 945,
#         "Men's Health": 636,
#         "Erectile Dysfunction": 202,
#         "Mental Health": 437,
#         "Anxiety & Stress": 639,
#         "Depression": 640,
#         "Learning & Developmental Disabilities": 641,
#         "ADD & ADHD": 642,
#         "Nursing": 418,
#         "Assisted Living & Long Term Care": 649,
#         "Nutrition": 456,
#         "Special & Restricted Diets": 457,
#         "Cholesterol Issues": 643,
#         "Vitamins & Supplements": 237,
#         "Oral & Dental Care": 245,
#         "Pediatrics": 645,
#         "Pharmacy": 248,
#         "Drugs & Medications": 646,
#         "Public Health": 947,
#         "Health Policy": 1256,
#         "Occupational Health & Safety": 644,
#         "Poisons & Overdoses": 946,
#         "Vaccines & Immunizations": 1263,
#         "Reproductive Health": 195,
#         "Birth Control": 198,
#         "Erectile Dysfunction": 202,
#         "Infertility": 647,
#         "OBGYN": 558,
#         "Pregnancy & Maternity": 401,
#         "Sex Education & Counseling": 536,
#         "Sexual Enhancement": 1236,
#         "Sexually Transmitted Diseases": 421,
#         "AIDS & HIV": 625,
#         "Substance Abuse": 257,
#         "Drug & Alcohol Testing": 1351,
#         "Drug & Alcohol Treatment": 1350,
#         "Smoking & Smoking Cessation": 1237,
#         "Steroids & Performance-Enhancing Drugs": 1235,
#         "Vision Care": 246,
#         "Eyeglasses & Contacts": 1224,
#         "Women's Health": 648,
#         "OBGYN": 558,
#         "Pregnancy & Maternity": 401,
#         "Hobbies & Leisure": 65,
#         "Antiques & Collectibles": 64,
#         "Bowling": 1016,
#         "Clubs & Nightlife": 188,
#         "Clubs & Organizations": 189,
#         "Contests, Awards & Prizes": 1276,
#         "Film & TV Awards": 1108,
#         "Lottery & Sweepstakes": 364,
#         "Crafts": 284,
#         "Fiber & Textile Arts": 1230,
#         "Cycling": 458,
#         "Bicycles & Accessories": 1191,
#         "Outdoors": 688,
#         "Equestrian": 568,
#         "Fishing": 462,
#         "Hiking & Camping": 542,
#         "Hunting & Shooting": 461,
#         "Paintball": 786,
#         "Pets & Animals": 66,
#         "Animal Products & Services": 882,
#         "Animal Welfare": 883,
#         "Pet Food & Supplies": 379,
#         "Veterinarians": 380,
#         "Pets": 563,
#         "Birds": 884,
#         "Cats": 885,
#         "Dogs": 886,
#         "Exotic Pets": 607,
#         "Fish & Aquaria": 887,
#         "Horses": 888,
#         "Rabbits & Rodents": 889,
#         "Reptiles & Amphibians": 890,
#         "Wildlife": 119,
#         "Insects & Entomology": 1278,
#         "Zoos-Aquariums-Preserves": 1009,
#         "Photographic & Digital Arts": 439,
#         "Camera & Photo Equipment": 573,
#         "Binoculars, Telescopes & Optical Devices": 1384,
#         "Cameras & Camcorders": 306,
#         "Camcorders": 308,
#         "Camera Lenses": 1383,
#         "Cameras": 307,
#         "Photo & Video Software": 577,
#         "Video File Formats & Codecs": 1315,
#         "Radio Control & Modeling": 787,
#         "Recreational Aviation": 999,
#         "Personal Aircraft": 1147,
#         "Running & Walking": 541,
#         "Special Occasions": 977,
#         "Gifts & Special Event Items": 70,
#         "Cards & Greetings": 100,
#         "Flowers": 323,
#         "Gifts": 99,
#         "Party & Holiday Supplies": 324,
#         "Holidays & Seasonal Events": 678,
#         "Birthdays & Name Days": 1270,
#         "Carnival & Mardi Gras": 1246,
#         "Christian Holidays": 1274,
#         "Christmas": 1078,
#         "Easter": 1123,
#         "Halloween & October 31st": 1079,
#         "New Year's": 1080,
#         "Thanksgiving": 1081,
#         "Valentine's Day": 1082,
#         "Weddings": 1083,
#         "St. Patrick's Day": 1084,
#         "Mother's Day": 1085,
#         "Father's Day": 1086,
#         "Patriotic Holidays": 1087,
#         "Other Holidays & Special Occasions": 1088,
#         "Hobbies & Leisure": 65,
#         "Antiques & Collectibles": 64,
#         "Bowling": 1016,
#         "Clubs & Nightlife": 188,
#         "Clubs & Organizations": 189,
#         "Contests, Awards & Prizes": 1276,
#         "Film & TV Awards": 1108,
#         "Lottery & Sweepstakes": 364,
#         "Crafts": 284,
#         "Fiber & Textile Arts": 1230,
#         "Cycling": 458,
#         "Bicycles & Accessories": 1191,
#         "Outdoors": 688,
#         "Equestrian": 568,
#         "Fishing": 462,
#         "Hiking & Camping": 542,
#         "Hunting & Shooting": 461,
#         "Paintball": 786,
#         "Pets & Animals": 66,
#         "Animal Products & Services": 882,
#         "Animal Welfare": 883,
#         "Pet Food & Supplies": 379,
#         "Veterinarians": 380,
#         "Pets": 563,
#         "Birds": 884,
#         "Cats": 885,
#         "Dogs": 886,
#         "Exotic Pets": 607,
#         "Fish & Aquaria": 887,
#         "Horses": 888,
#         "Rabbits & Rodents": 889,
#         "Reptiles & Amphibians": 890,
#         "Wildlife": 119,
#         "Insects & Entomology": 1278,
#         "Zoos-Aquariums-Preserves": 1009,
#         "Photographic & Digital Arts": 439,
#         "Camera & Photo Equipment": 573,
#         "Binoculars, Telescopes & Optical Devices": 1384,
#         "Cameras & Camcorders": 306,
#         "Camcorders": 308,
#         "Camera Lenses": 1383,
#         "Cameras": 307,
#         "Photo & Video Software": 577,
#         "Video File Formats & Codecs": 1315,
#         "Radio Control & Modeling": 787,
#         "Recreational Aviation": 999,
#         "Personal Aircraft": 1147,
#         "Running & Walking": 541,
#         "Special Occasions": 977,
#         "Gifts & Special Event Items": 70,
#         "Cards & Greetings": 100,
#         "Flowers": 323,
#         "Gifts": 99,
#         "Party & Holiday Supplies": 324,
#         "Holidays & Seasonal Events": 678,
#         "Birthdays & Name Days": 1270,
#         "Carnival & Mardi Gras": 1246,
#         "Christian Holidays": 1274,
#         "Christmas": 1078,
#         "Easter": 1123,
#         "Halloween & October 31st": 1079,
#         "New Year's": 1080,
#         "Thanksgiving": 1081,
#         "Valentine's Day": 1082,
#         "Weddings": 1083,
#         "St. Patrick's Day": 1084,
#         "Mother's Day": 1085,
#         "Father's Day": 1086,
#         "Patriotic Holidays": 1087,
#         "Other Holidays & Special Occasions": 1088
#     }
# )


# keywords = st.sidebar.text_input("Enter keywords (comma separated)")
# kw_list = [keyword.strip() for keyword in keywords.split(',')]
# # Sidebar with dropdown list for geo selection
# st.sidebar.title("Select Geo Location")
# geo = st.sidebar.selectbox(
#     "Choose a geo location",
#     options={
#         "World": '',
#         "United States": 'US',
#         "Canada": 'CA',
#         "Brazil": 'BR',
#         "United Kingdom": 'GB',
#         "Germany": 'DE',
#         "France": 'FR',
#         "Italy": 'IT',
#         "Spain": 'ES',
#         "Australia": 'AU',
#         "India": 'IN',
#         "Japan": 'JP',
#         "South Korea": 'KR',
#         "Mexico": 'MX',
#         "Russia": 'RU',
#         "South Africa": 'ZA'
#     }
# )

# timeframe = '2022-01-01 2022-12-31'
# Fetch trending searches
pytrend = TrendReq(hl="en-US", tz=360)

# keywords = st.sidebar.text_input("Enter keywords (comma separated)")
# kw_list = [keyword.strip() for keyword in keywords.split(',')]


# Sidebar with dropdown list for geo selection
# if geo:

#     st.title("Today's Searches for " + country_label)
#     st.write("These values are from Google Trends and represent today's searches for the selected country.")
#     st.subheader("Today's Searches Table")
#     st.dataframe(today_searches, width=600, height=750)

# if keywords:
#     pytrend.build_payload(kw_list=kw_list)
#     df = pytrend.interest_by_region()
#     st.title("Interest by Region")
#     st.write(df)

if country:
    trending_searches = pytrend.trending_searches(pn=country)
    current_year = datetime.now().year
    top_charts = pytrend.top_charts(current_year - 2, hl="en-US", tz=300, geo="GLOBAL")
    st.title("Trending Searches for " + country_label)
    st.write(
        "These values are from Google Trends and represent the trending searches for the selected country. The data is for the specified timeframe."
    )
    st.subheader("Trending Searches Table")
    st.dataframe(trending_searches, width=600, height=750)
    html(
        """
            <script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script>
            <script type='text/javascript'>
            kofiwidget2.init('Buy me a Coffee', '#de2525', 'K3K714P40K');
            kofiwidget2.draw();
            </script>
        """
    )
    st.subheader(f"Top Charts Table Global {current_year - 2}")
    st.dataframe(top_charts, width=600, height=400)


# if keywords:
#     pytrend.build_payload(kw_list)
#     df = pytrend.interest_by_region(resolution='COUNTRY', inc_low_vol=False, inc_geo_code=False)
#     st.title("Interest Over Time")
#     st.write(df)
